### ISSUE TITLE
OSError: libc10_hip.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by PavanKumarMiriyala** [Looong01/pyg-rocm-build#1]
Hi, 

I'm facing an error with torch-scatter while running an example pytorch geometric code. 

I'm using 
1. Ubuntu 22.04.1 LTS
2. Python 3.10.6
3. torch 1.13.1
4. ROCM 5.4.2 

Installation is successful, but cannot an example code. 

`Traceback (most recent call last):
  File "/home/vmiriyal/pytorch_geometric/examples/gcn.py", line 7, in <module>
    import torch_geometric.transforms as T
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/__init__.py", line 1, in <module>
    import torch_geometric.utils
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/__init__.py", line 1, in <module>
    from .scatter import scatter
  File "/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/scatter.py", line 5, in <module>
    import torch_scatter
  File "/usr/local/lib/python3.10/dist-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 573, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libc10_hip.so: cannot open shared object file: No such file or directory
`

**Comment by PavanKumarMiriyala** [comment]
Hi, 

Any update on this?

**Comment by Looong01** [comment]
It seems that your rocm or hip installation is not completely.
Which command did you do before it returns this problem?

**Comment by Looong01** [comment]
> Sorry for so much time. GitHub does not send the notification email to me.
> It seems that your rocm or hip installation is not complete.
> Which command did you do before it returned this problem?

Sorry for so much time. GitHub does not send the notification email to me.
It seems that your rocm or hip installation is not complete.
Which command did you do before it returned this problem?

**Comment by Looong01** [comment]
> Hi,
> 
> Any update on this?

Sorry for so much time. GitHub does not send the notification email to me.
It seems that your rocm or hip installation is not complete.
Which command did you do before it returned this problem?

**Comment by Looong01** [comment]
I use ```python gcn.py```, and it run successfully.

```
(PyTorch) loong@home:~/Downloads/pytorch_geometric/examples$ python gcn.py
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.x
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.tx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.allx
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.y
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.ty
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.ally
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.graph
Downloading https://github.com/kimiyoung/planetoid/raw/master/data/ind.cora.test.index
Processing...
Done!
Epoch: 001, Loss: 1.9458, Train: 0.2857, Val: 0.1800, Test: 0.2030
Epoch: 002, Loss: 1.9417, Train: 0.4500, Val: 0.2980, Test: 0.3250
Epoch: 003, Loss: 1.9336, Train: 0.6071, Val: 0.3720, Test: 0.4130
Epoch: 004, Loss: 1.9258, Train: 0.6786, Val: 0.4160, Test: 0.4270
Epoch: 005, Loss: 1.9186, Train: 0.6857, Val: 0.4100, Test: 0.4270
Epoch: 006, Loss: 1.9118, Train: 0.7571, Val: 0.4760, Test: 0.4520
Epoch: 007, Loss: 1.9018, Train: 0.7643, Val: 0.5120, Test: 0.4800
Epoch: 008, Loss: 1.8946, Train: 0.8143, Val: 0.5320, Test: 0.5040
Epoch: 009, Loss: 1.8804, Train: 0.8429, Val: 0.5700, Test: 0.5440
Epoch: 010, Loss: 1.8706, Train: 0.8857, Val: 0.6160, Test: 0.5920
Epoch: 011, Loss: 1.8675, Train: 0.9000, Val: 0.6380, Test: 0.6380
Epoch: 012, Loss: 1.8523, Train: 0.9000, Val: 0.6580, Test: 0.6630
Epoch: 013, Loss: 1.8399, Train: 0.8929, Val: 0.6780, Test: 0.6650
Epoch: 014, Loss: 1.8315, Train: 0.9000, Val: 0.6800, Test: 0.6660
Epoch: 015, Loss: 1.8144, Train: 0.9071, Val: 0.6860, Test: 0.6680
Epoch: 016, Loss: 1.7984, Train: 0.9000, Val: 0.6820, Test: 0.6680
Epoch: 017, Loss: 1.7953, Train: 0.9000, Val: 0.6800, Test: 0.6680
Epoch: 018, Loss: 1.7846, Train: 0.9143, Val: 0.6820, Test: 0.6680
Epoch: 019, Loss: 1.7723, Train: 0.9071, Val: 0.6820, Test: 0.6680
Epoch: 020, Loss: 1.7635, Train: 0.9286, Val: 0.6840, Test: 0.6680
Epoch: 021, Loss: 1.7437, Train: 0.9143, Val: 0.6880, Test: 0.7000
Epoch: 022, Loss: 1.7242, Train: 0.9214, Val: 0.6860, Test: 0.7000
Epoch: 023, Loss: 1.7266, Train: 0.9214, Val: 0.6820, Test: 0.7000
Epoch: 024, Loss: 1.6978, Train: 0.9143, Val: 0.6840, Test: 0.7000
Epoch: 025, Loss: 1.6749, Train: 0.9071, Val: 0.6900, Test: 0.6950
Epoch: 026, Loss: 1.6739, Train: 0.9071, Val: 0.7000, Test: 0.6960
Epoch: 027, Loss: 1.6584, Train: 0.9143, Val: 0.7020, Test: 0.6960
Epoch: 028, Loss: 1.6251, Train: 0.9071, Val: 0.6940, Test: 0.6960
Epoch: 029, Loss: 1.6272, Train: 0.9071, Val: 0.6980, Test: 0.6960
Epoch: 030, Loss: 1.6126, Train: 0.9071, Val: 0.7060, Test: 0.7040
Epoch: 031, Loss: 1.5836, Train: 0.9143, Val: 0.7120, Test: 0.7040
Epoch: 032, Loss: 1.5298, Train: 0.9143, Val: 0.7100, Test: 0.7040
Epoch: 033, Loss: 1.5698, Train: 0.9214, Val: 0.7120, Test: 0.7040
Epoch: 034, Loss: 1.5488, Train: 0.9286, Val: 0.7120, Test: 0.7040
Epoch: 035, Loss: 1.5310, Train: 0.9286, Val: 0.7100, Test: 0.7040
Epoch: 036, Loss: 1.5238, Train: 0.9357, Val: 0.7160, Test: 0.7150
Epoch: 037, Loss: 1.4982, Train: 0.9429, Val: 0.7200, Test: 0.7240
Epoch: 038, Loss: 1.4773, Train: 0.9500, Val: 0.7240, Test: 0.7360
Epoch: 039, Loss: 1.4381, Train: 0.9571, Val: 0.7360, Test: 0.7480
Epoch: 040, Loss: 1.4112, Train: 0.9571, Val: 0.7380, Test: 0.7490
Epoch: 041, Loss: 1.4095, Train: 0.9571, Val: 0.7420, Test: 0.7550
Epoch: 042, Loss: 1.4162, Train: 0.9571, Val: 0.7460, Test: 0.7580
Epoch: 043, Loss: 1.3663, Train: 0.9500, Val: 0.7500, Test: 0.7660
Epoch: 044, Loss: 1.3685, Train: 0.9500, Val: 0.7580, Test: 0.7680
Epoch: 045, Loss: 1.3422, Train: 0.9500, Val: 0.7600, Test: 0.7680
Epoch: 046, Loss: 1.3214, Train: 0.9429, Val: 0.7580, Test: 0.7680
Epoch: 047, Loss: 1.2734, Train: 0.9500, Val: 0.7580, Test: 0.7680
Epoch: 048, Loss: 1.3126, Train: 0.9500, Val: 0.7580, Test: 0.7680
Epoch: 049, Loss: 1.2881, Train: 0.9500, Val: 0.7540, Test: 0.7680
Epoch: 050, Loss: 1.2626, Train: 0.9571, Val: 0.7540, Test: 0.7680
Epoch: 051, Loss: 1.2456, Train: 0.9571, Val: 0.7480, Test: 0.7680
Epoch: 052, Loss: 1.2071, Train: 0.9500, Val: 0.7540, Test: 0.7680
Epoch: 053, Loss: 1.2169, Train: 0.9571, Val: 0.7560, Test: 0.7680
Epoch: 054, Loss: 1.2218, Train: 0.9571, Val: 0.7520, Test: 0.7680
Epoch: 055, Loss: 1.1987, Train: 0.9571, Val: 0.7560, Test: 0.7680
Epoch: 056, Loss: 1.1463, Train: 0.9571, Val: 0.7580, Test: 0.7680
Epoch: 057, Loss: 1.1489, Train: 0.9643, Val: 0.7620, Test: 0.7750
Epoch: 058, Loss: 1.0924, Train: 0.9643, Val: 0.7620, Test: 0.7750
Epoch: 059, Loss: 1.0912, Train: 0.9643, Val: 0.7700, Test: 0.7790
Epoch: 060, Loss: 1.0829, Train: 0.9500, Val: 0.7600, Test: 0.7790
Epoch: 061, Loss: 1.1365, Train: 0.9500, Val: 0.7600, Test: 0.7790
Epoch: 062, Loss: 1.0798, Train: 0.9643, Val: 0.7620, Test: 0.7790
Epoch: 063, Loss: 1.0520, Train: 0.9643, Val: 0.7580, Test: 0.7790
Epoch: 064, Loss: 1.0099, Train: 0.9643, Val: 0.7600, Test: 0.7790
Epoch: 065, Loss: 1.0357, Train: 0.9571, Val: 0.7560, Test: 0.7790
Epoch: 066, Loss: 1.0183, Train: 0.9571, Val: 0.7600, Test: 0.7790
Epoch: 067, Loss: 0.9524, Train: 0.9571, Val: 0.7700, Test: 0.7790
Epoch: 068, Loss: 0.9861, Train: 0.9643, Val: 0.7740, Test: 0.7900
Epoch: 069, Loss: 0.9573, Train: 0.9643, Val: 0.7780, Test: 0.7970
Epoch: 070, Loss: 0.9000, Train: 0.9643, Val: 0.7800, Test: 0.8040
Epoch: 071, Loss: 0.9590, Train: 0.9643, Val: 0.7880, Test: 0.8070
Epoch: 072, Loss: 0.8974, Train: 0.9643, Val: 0.7840, Test: 0.8070
Epoch: 073, Loss: 0.9184, Train: 0.9643, Val: 0.7800, Test: 0.8070
Epoch: 074, Loss: 0.8707, Train: 0.9571, Val: 0.7860, Test: 0.8070
Epoch: 075, Loss: 0.9259, Train: 0.9571, Val: 0.7820, Test: 0.8070
Epoch: 076, Loss: 0.8730, Train: 0.9571, Val: 0.7840, Test: 0.8070
Epoch: 077, Loss: 0.8948, Train: 0.9714, Val: 0.7820, Test: 0.8070
Epoch: 078, Loss: 0.8724, Train: 0.9714, Val: 0.7780, Test: 0.8070
Epoch: 079, Loss: 0.8221, Train: 0.9786, Val: 0.7740, Test: 0.8070
Epoch: 080, Loss: 0.8098, Train: 0.9786, Val: 0.7780, Test: 0.8070
Epoch: 081, Loss: 0.7698, Train: 0.9786, Val: 0.7800, Test: 0.8070
Epoch: 082, Loss: 0.7809, Train: 0.9786, Val: 0.7800, Test: 0.8070
Epoch: 083, Loss: 0.7953, Train: 0.9786, Val: 0.7800, Test: 0.8070
Epoch: 084, Loss: 0.7868, Train: 0.9786, Val: 0.7820, Test: 0.8070
Epoch: 085, Loss: 0.7766, Train: 0.9786, Val: 0.7880, Test: 0.8070
Epoch: 086, Loss: 0.7624, Train: 0.9786, Val: 0.7740, Test: 0.8070
Epoch: 087, Loss: 0.7438, Train: 0.9786, Val: 0.7760, Test: 0.8070
Epoch: 088, Loss: 0.7470, Train: 0.9786, Val: 0.7780, Test: 0.8070
Epoch: 089, Loss: 0.7488, Train: 0.9786, Val: 0.7780, Test: 0.8070
Epoch: 090, Loss: 0.7023, Train: 0.9786, Val: 0.7800, Test: 0.8070
Epoch: 091, Loss: 0.6802, Train: 0.9786, Val: 0.7740, Test: 0.8070
Epoch: 092, Loss: 0.7212, Train: 0.9786, Val: 0.7740, Test: 0.8070
Epoch: 093, Loss: 0.6714, Train: 0.9786, Val: 0.7820, Test: 0.8070
Epoch: 094, Loss: 0.7165, Train: 0.9786, Val: 0.7820, Test: 0.8070
Epoch: 095, Loss: 0.6479, Train: 0.9786, Val: 0.7800, Test: 0.8070
Epoch: 096, Loss: 0.6366, Train: 0.9786, Val: 0.7760, Test: 0.8070
Epoch: 097, Loss: 0.6625, Train: 0.9786, Val: 0.7700, Test: 0.8070
Epoch: 098, Loss: 0.6653, Train: 0.9786, Val: 0.7740, Test: 0.8070
Epoch: 099, Loss: 0.6744, Train: 0.9857, Val: 0.7760, Test: 0.8070
Epoch: 100, Loss: 0.6547, Train: 0.9857, Val: 0.7760, Test: 0.8070
Epoch: 101, Loss: 0.6400, Train: 0.9929, Val: 0.7800, Test: 0.8070
Epoch: 102, Loss: 0.6497, Train: 0.9929, Val: 0.7800, Test: 0.8070
Epoch: 103, Loss: 0.6488, Train: 0.9857, Val: 0.7800, Test: 0.8070
Epoch: 104, Loss: 0.6380, Train: 0.9857, Val: 0.7780, Test: 0.8070
Epoch: 105, Loss: 0.6252, Train: 0.9857, Val: 0.7780, Test: 0.8070
Epoch: 106, Loss: 0.6282, Train: 0.9857, Val: 0.7780, Test: 0.8070
Epoch: 107, Loss: 0.6614, Train: 0.9857, Val: 0.7760, Test: 0.8070
Epoch: 108, Loss: 0.6519, Train: 0.9857, Val: 0.7680, Test: 0.8070
Epoch: 109, Loss: 0.6497, Train: 0.9857, Val: 0.7720, Test: 0.8070
Epoch: 110, Loss: 0.5704, Train: 0.9857, Val: 0.7720, Test: 0.8070
Epoch: 111, Loss: 0.6315, Train: 0.9857, Val: 0.7700, Test: 0.8070
Epoch: 112, Loss: 0.6458, Train: 0.9929, Val: 0.7680, Test: 0.8070
Epoch: 113, Loss: 0.5775, Train: 0.9929, Val: 0.7660, Test: 0.8070
Epoch: 114, Loss: 0.6391, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 115, Loss: 0.6158, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 116, Loss: 0.5698, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 117, Loss: 0.5502, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 118, Loss: 0.5472, Train: 0.9857, Val: 0.7820, Test: 0.8070
Epoch: 119, Loss: 0.5653, Train: 0.9857, Val: 0.7800, Test: 0.8070
Epoch: 120, Loss: 0.5527, Train: 0.9857, Val: 0.7820, Test: 0.8070
Epoch: 121, Loss: 0.5604, Train: 0.9857, Val: 0.7840, Test: 0.8070
Epoch: 122, Loss: 0.5733, Train: 0.9857, Val: 0.7880, Test: 0.8070
Epoch: 123, Loss: 0.5320, Train: 0.9929, Val: 0.7840, Test: 0.8070
Epoch: 124, Loss: 0.4771, Train: 0.9929, Val: 0.7840, Test: 0.8070
Epoch: 125, Loss: 0.5333, Train: 0.9929, Val: 0.7820, Test: 0.8070
Epoch: 126, Loss: 0.5719, Train: 0.9929, Val: 0.7800, Test: 0.8070
Epoch: 127, Loss: 0.5523, Train: 0.9929, Val: 0.7780, Test: 0.8070
Epoch: 128, Loss: 0.5221, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 129, Loss: 0.5272, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 130, Loss: 0.4935, Train: 0.9929, Val: 0.7700, Test: 0.8070
Epoch: 131, Loss: 0.4917, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 132, Loss: 0.4846, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 133, Loss: 0.5885, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 134, Loss: 0.5066, Train: 0.9929, Val: 0.7780, Test: 0.8070
Epoch: 135, Loss: 0.4784, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 136, Loss: 0.5135, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 137, Loss: 0.5279, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 138, Loss: 0.5504, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 139, Loss: 0.5620, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 140, Loss: 0.4789, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 141, Loss: 0.5244, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 142, Loss: 0.4353, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 143, Loss: 0.5215, Train: 0.9929, Val: 0.7780, Test: 0.8070
Epoch: 144, Loss: 0.4944, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 145, Loss: 0.5004, Train: 0.9929, Val: 0.7780, Test: 0.8070
Epoch: 146, Loss: 0.4232, Train: 1.0000, Val: 0.7780, Test: 0.8070
Epoch: 147, Loss: 0.4691, Train: 1.0000, Val: 0.7800, Test: 0.8070
Epoch: 148, Loss: 0.5094, Train: 1.0000, Val: 0.7780, Test: 0.8070
Epoch: 149, Loss: 0.4910, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 150, Loss: 0.4280, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 151, Loss: 0.4502, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 152, Loss: 0.4269, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 153, Loss: 0.4774, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 154, Loss: 0.5523, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 155, Loss: 0.4473, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 156, Loss: 0.5226, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 157, Loss: 0.5067, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 158, Loss: 0.5206, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 159, Loss: 0.4208, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 160, Loss: 0.4569, Train: 1.0000, Val: 0.7780, Test: 0.8070
Epoch: 161, Loss: 0.4278, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 162, Loss: 0.4743, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 163, Loss: 0.4533, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 164, Loss: 0.5090, Train: 0.9929, Val: 0.7740, Test: 0.8070
Epoch: 165, Loss: 0.4572, Train: 0.9929, Val: 0.7760, Test: 0.8070
Epoch: 166, Loss: 0.4067, Train: 1.0000, Val: 0.7800, Test: 0.8070
Epoch: 167, Loss: 0.4043, Train: 1.0000, Val: 0.7800, Test: 0.8070
Epoch: 168, Loss: 0.4124, Train: 1.0000, Val: 0.7820, Test: 0.8070
Epoch: 169, Loss: 0.4384, Train: 1.0000, Val: 0.7840, Test: 0.8070
Epoch: 170, Loss: 0.4441, Train: 1.0000, Val: 0.7880, Test: 0.8070
Epoch: 171, Loss: 0.4342, Train: 1.0000, Val: 0.7840, Test: 0.8070
Epoch: 172, Loss: 0.4359, Train: 1.0000, Val: 0.7840, Test: 0.8070
Epoch: 173, Loss: 0.4276, Train: 1.0000, Val: 0.7800, Test: 0.8070
Epoch: 174, Loss: 0.4389, Train: 1.0000, Val: 0.7780, Test: 0.8070
Epoch: 175, Loss: 0.4305, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 176, Loss: 0.4050, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 177, Loss: 0.4482, Train: 0.9929, Val: 0.7720, Test: 0.8070
Epoch: 178, Loss: 0.4385, Train: 0.9929, Val: 0.7660, Test: 0.8070
Epoch: 179, Loss: 0.4078, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 180, Loss: 0.4495, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 181, Loss: 0.4262, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 182, Loss: 0.4017, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 183, Loss: 0.4048, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 184, Loss: 0.4036, Train: 1.0000, Val: 0.7720, Test: 0.8070
Epoch: 185, Loss: 0.3428, Train: 1.0000, Val: 0.7700, Test: 0.8070
Epoch: 186, Loss: 0.3850, Train: 1.0000, Val: 0.7700, Test: 0.8070
Epoch: 187, Loss: 0.3592, Train: 1.0000, Val: 0.7720, Test: 0.8070
Epoch: 188, Loss: 0.4177, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 189, Loss: 0.4018, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 190, Loss: 0.4078, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 191, Loss: 0.3827, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 192, Loss: 0.3543, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 193, Loss: 0.4075, Train: 1.0000, Val: 0.7760, Test: 0.8070
Epoch: 194, Loss: 0.3883, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 195, Loss: 0.3212, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 196, Loss: 0.4002, Train: 1.0000, Val: 0.7720, Test: 0.8070
Epoch: 197, Loss: 0.3917, Train: 1.0000, Val: 0.7720, Test: 0.8070
Epoch: 198, Loss: 0.3705, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 199, Loss: 0.4083, Train: 1.0000, Val: 0.7740, Test: 0.8070
Epoch: 200, Loss: 0.3946, Train: 1.0000, Val: 0.7760, Test: 0.8070
```

**Comment by Looong01** [comment]
The file ```libc10_hip.so```
```
(base) loong@home:~$ sudo find / -name libc10_hip.so
/home/loong/anaconda3/envs/PyTorch/lib/python3.10/site-packages/torch/lib/libc10_hip.so
```
It seems that you did not install torch of ROCm version correctly.
Are you sure that you install ```torch-rocm```, not ```torch-cuda```?
You can try to reinstall it or recreate the env.

**Comment by PavanKumarMiriyala** [comment]
Yes, my torch installation with rocm 5.4.2 was messy. I cleaned it up and it is working now. Thanks @Looong01

**Comment by Looong01** [comment]
Right.
